//! Build script for alynxis-core.
//!
//! Computes SHA-256 digests of every Zone A source file (Section 9 of the
//! Alynxis project brief) at compile time, from the exact file contents that
//! are about to be compiled into this binary, and bakes them into a
//! generated Rust source file that `src/core/zones.rs` includes via
//! `include!(concat!(env!("OUT_DIR"), "/zone_a_hashes.rs"))`.
//!
//! `zones::verify_integrity()` re-reads these same files from disk at every
//! process startup and refuses to boot if any digest no longer matches —
//! this is the "SHA-256 hash verification... refuses to boot if Zone A has
//! been tampered with" requirement from Section 9.
//!
//! **Since Part 4:** paths in `ZONE_A_FILES` are resolved relative to the
//! **workspace root**, not this crate's own manifest directory — Part 4
//! needed a Zone A file living in `alynxis-values` (`wellbeing.rs`, the
//! `wellbeing_of_others` hard floor, Section 3e), and rather than give
//! every crate that needs Zone A protection its own independent
//! build.rs/verifier, one canonical verifier (owned here, in the
//! foundational crate, called first at boot) now covers Zone A files
//! anywhere in the workspace. `alynxis-core`'s `CARGO_MANIFEST_DIR` is
//! always `<workspace_root>/crates/alynxis-core`, so walking up two
//! parent directories reaches the workspace root reliably as long as that
//! `crates/<name>` layout holds — which the workspace `Cargo.toml`
//! already establishes as the fixed convention.
//!
//! See the doc comment at the top of `src/core/zones.rs` for the honest
//! limitation of this mechanism (it does not, alone, stop a self-
//! modification engine that edits a Zone A file and then triggers its own
//! rebuild — that threat model requires Part 9a's self-mod engine to
//! consult and obey `zones::is_zone_a()` before writing anything).

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::Path;

/// The complete Zone A file set (Section 9: "Zone A — Frozen... In the
/// earlier build this was concretely two files, `harm_check.rs` and
/// `zones.rs`"). `admin.rs` is added because it implements the
/// credential-verification logic Section 3c requires to be
/// architecturally inaccessible to Alynxis itself. `wellbeing.rs` (Part 4)
/// is added because Section 3e requires the `wellbeing_of_others` floor to
/// "live in Zone A... not merely weighted heavily within the ordinary
/// emergent value system." All paths are workspace-root-relative.
const ZONE_A_FILES: &[&str] = &[
    "crates/alynxis-core/src/core/zones.rs",
    "crates/alynxis-core/src/core/harm_check.rs",
    "crates/alynxis-core/src/core/admin.rs",
    "crates/alynxis-values/src/wellbeing.rs",
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let workspace_root = Path::new(&manifest_dir)
        .parent() // crates/
        .and_then(|p| p.parent()) // workspace root
        .unwrap_or_else(|| {
            panic!(
                "build.rs: expected CARGO_MANIFEST_DIR ({manifest_dir}) to be \
                 <workspace_root>/crates/alynxis-core, but it has fewer than two parent \
                 directories"
            )
        })
        .to_path_buf();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("zone_a_hashes.rs");

    let mut generated = String::new();
    generated.push_str("// AUTO-GENERATED by build.rs — DO NOT EDIT BY HAND.\n");
    generated
        .push_str("// SHA-256 digests of Zone A source files, computed at compile time from\n");
    generated.push_str("// the exact files that were compiled into this binary (Section 9).\n");
    generated
        .push_str("// Paths are workspace-root-relative (see build.rs module doc comment).\n\n");
    generated.push_str(&format!(
        "pub static ZONE_A_WORKSPACE_ROOT: &str = {:?};\n\n",
        workspace_root.display().to_string()
    ));
    generated.push_str("pub static ZONE_A_FILE_HASHES: &[(&str, &str)] = &[\n");

    for rel_path in ZONE_A_FILES {
        let full_path = workspace_root.join(rel_path);
        let contents = fs::read(&full_path).unwrap_or_else(|e| {
            panic!(
                "build.rs: failed to read Zone A file {}: {}",
                full_path.display(),
                e
            )
        });
        let mut hasher = Sha256::new();
        hasher.update(&contents);
        let digest = hasher.finalize();
        let hex_digest = hex_encode(&digest);
        generated.push_str(&format!("    ({rel_path:?}, {hex_digest:?}),\n"));

        // Re-run this build script whenever a Zone A file changes, so the
        // baked-in hash always reflects exactly what was last compiled —
        // never a stale hash from a previous build.
        println!("cargo:rerun-if-changed={}", full_path.display());
    }

    generated.push_str("];\n");

    fs::write(&dest_path, generated).expect("failed to write zone_a_hashes.rs");
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}
