//! Zone A — FROZEN. Part of Zone A itself (Section 9).
//!
//! This file implements:
//!   1. The zone registry: which source files belong to Zone A / B / C.
//!   2. `verify_integrity()`: re-hashes Zone A's own source files at every
//!      startup and refuses to boot on mismatch.
//!   3. `classify_path()` / `is_zone_a()`: the permission-check API that any
//!      future self-modification pathway (Part 9a) MUST consult and obey
//!      before writing to any file. This function is the actual load-
//!      bearing enforcement point per Section 9's requirement that "the
//!      permission check that enforces this lives inside Zone A itself" —
//!      not the hash check below, which is a complementary but distinct
//!      safeguard.
//!
//! **Since Part 4:** Zone A file resolution covers the whole workspace, not
//! just this crate — see `build.rs`'s module doc comment for why (Part 4
//! needed `alynxis-values/src/wellbeing.rs`, the `wellbeing_of_others` hard
//! floor, Section 3e, to be genuinely Zone A rather than inventing a second
//! independent verifier in that crate).
//!
//! ## Honest limitation, recorded for future sessions
//!
//! The SHA-256 boot-integrity check in this file detects a Zone A source
//! file being modified *between compiles* (e.g. direct filesystem
//! tampering, or a bug elsewhere writing where it shouldn't). It does
//! **not**, by itself, stop a determined self-modification engine that
//! (a) edits a Zone A file and (b) triggers its own rebuild — because
//! `build.rs` would simply re-hash the new (tampered) content and bake in a
//! hash that matches it, and the runtime check would then pass against the
//! tampered file.
//!
//! The actual hard boundary against *that* threat model has to be enforced
//! earlier in the pipeline: Part 9a's self-modification engine must call
//! `zones::is_zone_a()` before proposing or applying any change, and must
//! categorically refuse if the answer is `true` — full stop, no override,
//! no exception, per Section 9's requirement that this "cannot be reasoned
//! around, patched out, or bootstrapped past." `is_zone_a()` living inside
//! this Zone-A-hash-verified file is what makes that refusal itself
//! tamper-resistant. The boot-time hash check in this file remains valuable
//! as a second, independent detection layer against tampering that doesn't
//! go through the self-modification engine at all — it is not redundant,
//! just not sufficient alone against every threat model. Flagging this now
//! so Part 9a is designed with this fully in mind, not discovered as a gap
//! later.

use crate::error::{AlynxisError, Result};
use sha2::{Digest, Sha256};
use std::path::Path;

// Generated by build.rs from the exact files compiled into this binary:
//   pub static ZONE_A_WORKSPACE_ROOT: &str = "...";
//   pub static ZONE_A_FILE_HASHES: &[(&str, &str)] = &[...];
include!(concat!(env!("OUT_DIR"), "/zone_a_hashes.rs"));

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZoneId {
    /// Frozen. HarmCheck (Part 11), the `wellbeing_of_others` floor
    /// (Section 3e, `alynxis-values/src/wellbeing.rs`, Part 4), the
    /// shutdown handler (Part 9a-era), the admin-override mechanism, and
    /// the zone-membership registries themselves. Hash-verified at boot.
    /// Categorically off-limits to self-modification (Section 9a) —
    /// enforced via `is_zone_a()` below.
    A,
    /// Supervised. Core reasoning/learning rules (Main Loop orchestration,
    /// MemorySystem structure rules, WorldModel learning rules,
    /// CritiqueEngine heuristics, attention thresholds, emotional-
    /// regulation rules). Self-modification allowed but changes are
    /// logged and queued for human review before taking effect, gated by
    /// `Config::require_zone_b_review` (Section 9a).
    B,
    /// Free. Domain knowledge, concept labels, learned skills,
    /// communication patterns, task-specific procedures. Freely
    /// modifiable through ordinary learning; changes are passively
    /// logged but need no approval.
    C,
}

/// Which source files belong to which zone. Per Section 9, "the zone-
/// membership registries themselves" are Zone A content — this table lives
/// inside `zones.rs`, a hash-verified Zone A file, so changing it means
/// changing a Zone A file (subject to the same protection as everything
/// else here). Extend this as later parts add files; never remove an `A`
/// entry without Lynx's explicit direction. Anything not listed here
/// defaults to `ZoneId::C` (see `classify_path`), matching Section 9's own
/// framing of Zone C as "everything else." Entries are matched by path
/// *suffix* (see `classify_path`), so it doesn't matter here whether a
/// given entry is written crate-relative or workspace-relative — both
/// resolve correctly against real paths encountered at runtime.
pub static ZONE_REGISTRY: &[(&str, ZoneId)] = &[
    ("src/core/zones.rs", ZoneId::A),
    ("src/core/harm_check.rs", ZoneId::A),
    ("src/core/admin.rs", ZoneId::A),
    // Part 4: the wellbeing_of_others hard floor (Section 3e) must "live
    // in Zone A... not merely weighted heavily within the ordinary
    // emergent value system." This is the first Zone A file outside
    // alynxis-core — see build.rs's module doc comment for how hash
    // verification now reaches across the whole workspace to cover it.
    ("crates/alynxis-values/src/wellbeing.rs", ZoneId::A),
    // Part 2: concept-generalization ingestion is exactly what Section 9
    // names as Zone B content — "WorldModel learning rules" (the rule for
    // how concepts get created and linked), as distinct from the ordinary
    // graph data/storage code around it, which stays Zone C.
    ("crates/alynxis-worldmodel/src/ingestion.rs", ZoneId::B),
    // Part 3: memory tier-transition mechanics are exactly what Section 9
    // separately names as Zone B content — "MemorySystem structure rules"
    // — as distinct from the ordinary episode/pattern storage code around
    // it, which stays Zone C.
    ("crates/alynxis-memory/src/tiers.rs", ZoneId::B),
];

/// Classifies a path by matching its suffix against `ZONE_REGISTRY`.
/// Suffix matching (rather than requiring an exact absolute-path match) is
/// deliberate: it keeps this working regardless of where the crate is
/// checked out on disk, which matters once Part 9a's self-modification
/// engine needs to classify paths it constructs itself.
pub fn classify_path(path: &Path) -> ZoneId {
    let path_str = path.to_string_lossy().replace('\\', "/");
    for (rel, zone) in ZONE_REGISTRY {
        if path_str.ends_with(*rel) {
            return *zone;
        }
    }
    ZoneId::C
}

/// The load-bearing permission check described in this file's module doc
/// comment. Part 9a's self-modification engine MUST call this before
/// proposing or applying any change and MUST categorically refuse if it
/// returns `true`.
pub fn is_zone_a(path: &Path) -> bool {
    matches!(classify_path(path), ZoneId::A)
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Re-hashes every Zone A source file (resolved relative to the compile-
/// time workspace root) and compares against the hashes baked in by
/// `build.rs`. Returns an error — and callers MUST refuse to boot on that
/// error — if any file is missing or its content has changed since
/// compile time.
pub fn verify_integrity() -> Result<()> {
    verify_integrity_at(Path::new(ZONE_A_WORKSPACE_ROOT))
}

/// Same check as `verify_integrity()`, but against an arbitrary root
/// directory rather than the compile-time workspace root. Exists so tests
/// can exercise the mismatch/missing-file paths without touching the real
/// source tree.
pub fn verify_integrity_at(workspace_root: &Path) -> Result<()> {
    for (rel_path, expected_hex) in ZONE_A_FILE_HASHES {
        let full_path = workspace_root.join(rel_path);
        let contents = std::fs::read(&full_path).map_err(|_| AlynxisError::ZoneFileMissing {
            path: full_path.clone(),
        })?;
        let mut hasher = Sha256::new();
        hasher.update(&contents);
        let actual = hex_encode(&hasher.finalize());
        if &actual != expected_hex {
            return Err(AlynxisError::ZoneIntegrityFailure {
                file: rel_path.to_string(),
                expected: expected_hex.to_string(),
                actual,
            });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn real_zone_a_files_pass_integrity_check() {
        // End-to-end happy-path test: build.rs has already hashed the real
        // files on disk as part of this very compilation, so this should
        // always succeed unless something is genuinely wrong.
        verify_integrity()
            .expect("Zone A integrity check should pass against its own freshly-compiled source");
    }

    #[test]
    fn tampered_content_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        let core_dir = dir.path().join("crates/alynxis-core/src/core");
        let values_dir = dir.path().join("crates/alynxis-values/src");
        std::fs::create_dir_all(&core_dir).unwrap();
        std::fs::create_dir_all(&values_dir).unwrap();
        // Different content than what build.rs actually hashed, under the
        // same workspace-relative paths, simulating tampering.
        std::fs::write(core_dir.join("zones.rs"), b"tampered content").unwrap();
        std::fs::write(core_dir.join("harm_check.rs"), b"tampered content").unwrap();
        std::fs::write(core_dir.join("admin.rs"), b"tampered content").unwrap();
        std::fs::write(values_dir.join("wellbeing.rs"), b"tampered content").unwrap();

        let result = verify_integrity_at(dir.path());
        assert!(matches!(
            result,
            Err(AlynxisError::ZoneIntegrityFailure { .. })
        ));
    }

    #[test]
    fn missing_file_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        // Empty directory — none of the expected files exist.
        let result = verify_integrity_at(dir.path());
        assert!(matches!(result, Err(AlynxisError::ZoneFileMissing { .. })));
    }

    #[test]
    fn classify_known_zone_a_files() {
        assert_eq!(classify_path(Path::new("src/core/zones.rs")), ZoneId::A);
        assert_eq!(
            classify_path(Path::new("src/core/harm_check.rs")),
            ZoneId::A
        );
        assert_eq!(classify_path(Path::new("src/core/admin.rs")), ZoneId::A);
        assert!(is_zone_a(Path::new("/some/prefix/src/core/admin.rs")));
        assert_eq!(
            classify_path(Path::new("crates/alynxis-values/src/wellbeing.rs")),
            ZoneId::A
        );
        assert!(is_zone_a(Path::new(
            "crates/alynxis-values/src/wellbeing.rs"
        )));
    }

    #[test]
    fn classify_known_zone_b_files() {
        assert_eq!(
            classify_path(Path::new("crates/alynxis-worldmodel/src/ingestion.rs")),
            ZoneId::B
        );
        assert!(!is_zone_a(Path::new(
            "crates/alynxis-worldmodel/src/ingestion.rs"
        )));
        assert_eq!(
            classify_path(Path::new("crates/alynxis-memory/src/tiers.rs")),
            ZoneId::B
        );
    }

    #[test]
    fn unknown_paths_default_to_zone_c() {
        assert_eq!(classify_path(Path::new("src/config.rs")), ZoneId::C);
        assert_eq!(
            classify_path(Path::new("totally/unrelated/file.rs")),
            ZoneId::C
        );
        assert!(!is_zone_a(Path::new("src/config.rs")));
    }
}
